# Travis-CI Build for rugged
# see travis-ci.org for details

language: ruby

# Ruby versions to test against
rvm:
  - 1.8.7
  - 1.9.3

# Run the Build script
script:
 - git submodule update --init
 - mkdir cmake-build
 - cd cmake-build
 - cmake -DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./libgit2-bin ../libgit2
 - export LD_LIBRARY_PATH=$PWD/libgit2-bin/lib
 - cmake --build . --target install
 - cd ..

# Only watch the development branch
branches:
 only:
   - development
   
# Notify development list when needed
notifications:
 recipients:
   - carlosmn@gmail.com
 email:
   on_success: change
   on_failure: always
